SELECT 
    TSR_FACT_LINKED_KEYS_UITI,
    COUNT(DISTINCT UTI) AS UTI_CNT,
    CONCAT_WS(';', COLLECT_SET(CONCAT(UTI, ' : ', COALESCE(SUBSTRING(valuation_timestamp, 1, 10), 'NOT RPTD')))) AS UTI_LIST,
    MAX(TO_DATE(SUBSTRING(valuation_timestamp, 1, 10))) AS max_val_ts
FROM GFOLYREG_WORK.APP_REGHUB_ESMA_CORRECT_SUBMISSION_UITI_ENRICHED
GROUP BY TSR_FACT_LINKED_KEYS_UITI
HAVING COUNT(DISTINCT UTI) > 1;
